### ISSUE TITLE
添加你的仓库到CrossCore-Internationalizer的readme

### ISSUE THREAD

**Issue by AXiX-official** [wu-vincent/crosscore-custom#1]
你可以在我的仓库提交一个pr，自行修改readme以添加此仓库为相关项目。因为我现在外出不方便自行添加。

**Comment by wu-vincent** [comment]
好的，感谢，等我明天起来弄一下，如果你不介意的话，我可以把自动发布custom包的github workflow一起发一个pr

**Comment by AXiX-official** [comment]
可以
